# conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for pangaea.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f conda_env.yml

name: pangaea
channels:
- conda-forge
- defaults
dependencies:
- dask
- gazar
- netcdf4
- libgdal 2.2.*
- gdal 2.2.*
# pynio does not work on Windows
#- pynio
- wrf-python
