# conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for pangaea.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f conda_env.yml

name: pangaea
channels:
- conda-forge
- defaults
dependencies:
- python=2
- affine
- appdirs
# pynio does not work on Windows
#- pynio
- pyproj
#- sloot
- wrf-python
